In [1]:
import sys
import os
import cv2
import itertools
import pickle
import numpy as np
from PIL import Image, ImageFilter

sys.path

['',
 '/home/huyqt7/Softwares/anaconda2/lib/python27.zip',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7/plat-linux2',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7/lib-tk',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7/lib-old',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7/lib-dynload',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7/site-packages',
 '/home/huyqt7/Softwares/anaconda2/lib/python2.7/site-packages/IPython/extensions',
 '/home/huyqt7/.ipython']

In [2]:
def deskew(img):
    m = cv2.moments(img)
    SZ=40
    if abs(m['mu02']) < 1e-2:
        # no deskewing needed. 
        return img.copy()
    # Calculate skew based on central momemts. 
    skew = m['mu11']/m['mu02']
    # Calculate affine transform to correct skewness. 
    M = np.float32([[1, skew, -0.5*SZ*skew], [0, 1, 0]])
    # Apply affine transform
    img = cv2.warpAffine(img, M, (SZ, SZ), flags=cv2.WARP_INVERSE_MAP | cv2.INTER_LINEAR)
    return img

In [3]:
structures = [x for x in os.walk('../Caltech10/')]

In [4]:
image = Image.open("../Caltech10/ant/image_0002.jpg")
im_data = np.asarray( image, dtype="int32" )
print im_data
img = image.convert("L").filter(ImageFilter.GaussianBlur(radius = 1))
im_data = np.asarray( img, dtype="int32" )
print im_data

[[[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 ..., 
 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]
  ..., 
  [0 0 0]
  [0 0 0]
  [0 0 0]]]
[[0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 ..., 
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]
 [0 0 0 ..., 0 0 0]]


In [5]:
def pickle_operating(fname, item):
    # save or load the pickle file.
    file_name = '%s.pickle' % fname
    print(file_name)
    if not item:
        with open(file_name, 'rb') as fs:
            item = pickle.load(fs)
            return item
    else:
        with open(file_name, 'wb') as fs:
            pickle.dump(item, fs, protocol=pickle.HIGHEST_PROTOCOL)

In [10]:
def save_imgs(folders):
    dataset = {'categories': {}, 'data': []}
    data = []
    label = 0
    for f in folders:
        dataset['categories'][f[0]] = label
        for i in f[2]:
            image = Image.open("%s/%s"%(f[0], i))
            img = image.convert("L").filter(ImageFilter.GaussianBlur(radius = 2))
            im_data = np.asarray( img, dtype="int64" )
            dataset['data'].append((im_data, label))
        label += 1
    return dataset

In [11]:
dataset = save_imgs(structures)
pickle_operating('dataset', dataset)
dataset_1 = pickle_operating('dataset', None)
print(dataset_1)

dataset.pickle
dataset.pickle
{'data': [(array([[252, 251, 249, ..., 248, 249, 252],
       [251, 250, 247, ..., 246, 248, 251],
       [250, 248, 243, ..., 243, 247, 250],
       ..., 
       [245, 244, 242, ..., 247, 249, 249],
       [247, 246, 245, ..., 249, 250, 249],
       [248, 248, 247, ..., 250, 250, 250]]), 1), (array([[214, 214, 213, ...,   0,   0,   0],
       [213, 213, 213, ...,   0,   0,   0],
       [212, 212, 212, ...,   0,   0,   0],
       ..., 
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0],
       [  0,   0,   0, ...,   0,   0,   0]]), 1), (array([[255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       ..., 
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255],
       [255, 255, 255, ..., 255, 255, 255]]), 1), (array([[ 68,  64,  60, ..., 116, 126, 133],
       [ 61,  58,  56, ..., 104, 114, 120],
       [ 52,  52,  

In [8]:
files = []
for i in range(1,11):
    files.append("FDDB-fold-%02d-ellipseList.txt"%i)
print files

['FDDB-fold-01-ellipseList.txt', 'FDDB-fold-02-ellipseList.txt', 'FDDB-fold-03-ellipseList.txt', 'FDDB-fold-04-ellipseList.txt', 'FDDB-fold-05-ellipseList.txt', 'FDDB-fold-06-ellipseList.txt', 'FDDB-fold-07-ellipseList.txt', 'FDDB-fold-08-ellipseList.txt', 'FDDB-fold-09-ellipseList.txt', 'FDDB-fold-10-ellipseList.txt']
